AWSTemplateFormatVersion: "2010-09-09"
Description: Template for S3 Photo Index Gallery (S3-PIG) service

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  PhotoBucketName:
    Type: String
    Default: as3-pig
    Description: Bucket name for storing images and hosting Photo Index Gallery (S3-PIG)

Resources:
  S3BucketPhotoHosting:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref PhotoBucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  S3PigFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Detects uploaded image attributes and saves for use with Photo Index Gallery (S3-PIG)
      Handler: s3pigfunction.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Policies:
        - AmazonS3FullAccess
        - AmazonRekognitionReadOnlyAccess
      MemorySize: 128
      Timeout: 30
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: S3BucketPhotoHosting
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketPhotoHosting
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: S3BucketPhotoHosting
                  - "/*"
            Principal: "*"
