AWSTemplateFormatVersion: "2010-09-09"
Description: Template for S3 Photo Index Gallery (S3-PIG) service

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  PhotoBucketName:
    Type: String
    Default: as3-pig
    Description: Bucket name for storing images and hosting Photo Index Gallery (S3-PIG)

Resources:
  S3PigFunctionCreate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Detects uploaded image attributes and saves for use with Photo Index Gallery (S3-PIG)
      Handler: s3pigfunction-c.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AmazonRekognitionReadOnlyAccess
      MemorySize: 128
      Timeout: 30
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: S3BucketPhotoHosting
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'
                  - Name: prefix
                    Value: 'img/'

  S3PigFunctionDelete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Deletes image record from Photo Index Gallery (S3-PIG) JSON config
      Handler: s3pigfunction-d.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 10
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: S3BucketPhotoHosting
            Events:
              - 's3:ObjectRemoved:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'
                  - Name: prefix
                    Value: 'img/'

  S3BucketPhotoHosting:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PhotoBucketName
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          -
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - "GET"
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketPhotoHosting
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: S3BucketPhotoHosting
                  - "/*"
            Principal: "*"

  S3PigDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "S3PigImageAttributes"
      KeySchema:
        -
          AttributeName: 'FileName'
          KeyType: HASH
      AttributeDefinitions:
        -
          AttributeName: 'FileName'
          AttributeType: 'S'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  S3Copy:
    Type: Custom::S3Copy
    Properties:
      Region: !Ref 'AWS::Region'
      ServiceToken: !GetAtt FunctionGitToS3Copy.Arn
      TargetS3BucketName:
        Ref: S3BucketPhotoHosting
      SourceUrls:
        - 'https://raw.githubusercontent.com/apavlenko69/AS3-PIG/master/index.html'
        - 'https://raw.githubusercontent.com/apavlenko69/AS3-PIG/master/js/s3pi_grid.js'
        - 'https://raw.githubusercontent.com/apavlenko69/AS3-PIG/master/css/grid_gallery.css'
        - 'https://raw.githubusercontent.com/apavlenko69/AS3-PIG/master/img/readme.txt'

  FunctionGitToS3Copy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Copies static files from Github to S3 bucket as part of deploy
      Handler: gittos3copy.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Policies:
        - AmazonS3FullAccess
      MemorySize: 128
      Timeout: 30

